import { writeFileSync } from 'node:fs'
import path from 'node:path'
import type { JsonSchema, Release } from '@platform/sdk'
import { createRegistryClient } from './registry'

/** `mfe types`: writes `platform-registry.d.ts` augmenting `Register` from the release (§9.2 item 7). Catalog-backed kinds come later. */
export async function generateTypes(options: { root: string; registry: string; token?: string; release?: Release }) {
  const release = options.release ?? (await createRegistryClient({ url: options.registry, token: options.token }).release())
  const paths: string[] = []
  const widgets: string[] = []
  for (const m of Object.values(release.mfes)) {
    if (m.kind === 'app') {
      for (const [p, decl] of Object.entries(m.paths)) {
        const params = decl.params ? schemaToType(decl.params) : 'Record<string, never>'
        const search = decl.search ? `; search?: ${schemaToType(decl.search)}` : ''
        paths.push(`    ${JSON.stringify(p)}: { params: ${params}${search} }`)
      }
    } else {
      const events = Object.entries(m.events).map(([k, s]) => `${JSON.stringify(k)}: ${schemaToType(s)}`).join('; ')
      widgets.push(`    ${JSON.stringify(m.id)}: { contract: ${m.contract.version}; props: ${schemaToType(m.props)}; events: { ${events} } }`)
    }
  }
  const content = `// Generated by \`mfe types\` from release ${release.id}. Do not edit.
import '@platform/sdk'

declare module '@platform/sdk' {
  interface Register {
    paths: {
${paths.join('\n')}
    }
    widgets: {
${widgets.join('\n')}
    }
  }
}
`
  const file = path.join(options.root, 'platform-registry.d.ts')
  writeFileSync(file, content)
  return file
}

/** Enough of JSON Schema for path params, search, and widget props. */
export function schemaToType(schema: JsonSchema): string {
  const type = schema.type
  if (schema.enum && Array.isArray(schema.enum)) return schema.enum.map(v => JSON.stringify(v)).join(' | ')
  if (Array.isArray(schema.anyOf)) return (schema.anyOf as JsonSchema[]).map(schemaToType).join(' | ')
  if (Array.isArray(schema.oneOf)) return (schema.oneOf as JsonSchema[]).map(schemaToType).join(' | ')
  if (type === 'object' || schema.properties) {
    const props = (schema.properties ?? {}) as Record<string, JsonSchema>
    const required = new Set((schema.required as string[] | undefined) ?? [])
    const entries = Object.entries(props).map(([k, s]) => `${JSON.stringify(k)}${required.has(k) ? '' : '?'}: ${schemaToType(s)}`)
    return `{ ${entries.join('; ')} }`
  }
  if (type === 'array') return `Array<${schema.items ? schemaToType(schema.items as JsonSchema) : 'unknown'}>`
  if (type === 'string') return 'string'
  if (type === 'number' || type === 'integer') return 'number'
  if (type === 'boolean') return 'boolean'
  if (type === 'null') return 'null'
  if (Array.isArray(type)) return type.map(t => schemaToType({ ...schema, type: t })).join(' | ')
  return 'unknown'
}
